fon:
  fon_path: /Users/admin/PycharmProjects/AirPlan/Data/menu/fon.jpg
  fon_stylesheet: "QMainWindow {\n
                   background-image: url('{}');\n
                   background-repeat: no-repeat;\n
                   background-position: center;\n
                   }"

inputing_window:
  stylesheets:
    close_button: "QPushButton{\n
                  font: 20pt \"Times\";\n
                  color:#000000 ;\n
                  min-width: 94px; \n
                  max-width: 94px; \n
                  min-height: 94px; \n
                  max-height: 94px; \n
                  border-radius: 47px; \n
                  background-color: rgba(200, 14, 14, 1);\n
                  border: none ;\n
                  }\n
                  QPushButton:hover{\n
                  color:#ff0000 ;\n
                  background-color: rgba(255, 0, 0, 0.9);\n
                  }\n
                  QPushButton:pressed{\n
                  color: #a20707 ;\n
                  }"

    lineEdit_markers: "font: 22pt \"Times\";\n
                       color:#00FFFF ;\n
                       background-color: rgba(0, 0, 128, 0.2) ;\n
                       border: 4px inset blue;\n
                       "
    lineEdit_map: "font: 22pt \"Times\";\n
                   color:#00FFFF ;\n
                   background-color: rgba(0, 0, 128, 0.2) ;\n
                   border: 4px outset blue;\n
                   "
    lineEdit_countries: "font: 22pt \"Times\";\n
                        color:#00FFFF ;\n
                        background-color: rgba(0, 0, 128, 0.2) ;\n
                        border: 4px inset blue;\n
                        "
    label_1: "QLabel{\n
              font: 22pt \"Times\";\n
              color:#00FFFF ;\n
              border: none;\n
              }"
    label_2: "QLabel{\n
              font: 22pt \"Times\";\n
              color:#00FFFF ;\n
              border: none;\n
              }"

main_window:
  stylesheets:
    pathButton: "QPushButton{\n
                  font: 22pt \"Times\";\n
                  color:#00FFFF ;\n
                  background-color: rgba(0, 50, 50, 0.6);\n
                  border: none ;\n
                  }\n
                  QPushButton:hover{\n
                  color:#7CFC00 ;\n
                  background-color: rgba(0, 50, 50, 0.5);\n
                  }\n
                  QPushButton:pressed{\n
                  color: #CD853F ;\n
                  }"

    tourButton: "QPushButton{\n
                 font: 22pt \"Times\";\n
                 color:#00FFFF ;\n
                 background-color: rgba(0, 50, 50, 0.6);\n
                 border: none ;\n
                 }\n
                 QPushButton:hover{\n
                 color:#7CFC00 ;\n
                 background-color: rgba(0, 50, 50, 0.5);\n
                 }\n
                 QPushButton:pressed{\n
                 color: #CD853F ;\n
                 }"

    showButton: "QPushButton{\n
                 font: 22pt \"Times\";\n
                 color:#00FFFF ;\n
                 min-width: 90px; \n
                 max-width: 90px; \n
                 min-height: 90px; \n
                 max-height: 90px; \n
                 border-radius: 45px; \n
                 background-color: rgba(0, 50, 50, 0.7);\n
                 border: none ;\n
                 }\n
                 QPushButton:hover{\n
                 color:#7CFC00 ;\n
                 background-color: rgba(0, 50, 50, 0.6);\n
                 }\n
                 QPushButton:pressed{\n
                 color: #CD853F ;\n
                 }"

    radioButton: "QRadioButton{\n
                  font: 15pt \"Times\";\n
                  }"

    label_weather: "QLabel{\n
                    font: 20pt \"Times\";\n
                    color:#00FFFF ;\n
                    border: none;\n
                    }"

    label_distance: "QLabel{\n
                     font: 20pt \"Times\";\n
                     color:#00FFFF ;\n
                     border: none;\n
                     }"

    label_price: "QLabel{\n
                  font: 20pt \"Times\";\n
                  color:#00FFFF ;\n
                  border: none;\n
                  }"

  music: /Users/admin/PycharmProjects/AirPlan/Data/menu/menu.mp3

result_window:
  stylesheets:
    closeButton: "QPushButton{\n
                  font: 20pt \"Times\";\n
                  color:#000000 ;\n
                  min-width: 94px; \n
                  max-width: 94px; \n
                  min-height: 94px; \n
                  max-height: 94px; \n
                  border-radius: 47px; \n
                  background-color: rgba(200, 14, 14, 1);\n
                  border: none ;\n
                  }\n
                  QPushButton:hover{\n
                  color:#ff0000 ;\n
                  background-color: rgba(255, 0, 0, 0.9);\n
                  }\n
                  QPushButton:pressed{\n
                  color: #a20707 ;\n
                  }"

    label_city_from: "QLabel{\n
                      font: 22pt \"Times\";\n
                      color:#00FFFF ;\n
                      border: none;\n
                      }"

    label_city_to: "QLabel{\n
                    font: 22pt \"Times\";\n
                    color:#00FFFF ;\n
                    border: none;\n
                    }"

    label_priority: "QLabel{\n
                     font: 22pt \"Times\";\n
                     color:#00FFFF ;\n
                     border: none;\n
                     }"

    label_markers: "QLabel{\n
                    font: 22pt \"Times\";\n
                    color:#00FFFF ;\n
                    border: none;\n
                    }"

    label_map: "QLabel{\n
                font: 22pt \"Times\";\n
                color:#00FFFF ;\n
                border: none;\n
                }"

    lineEdit_city_from: "font: 22pt \"Times\";\n
                         color:#00FFFF ;\n
                         background-color: rgba(0, 0, 128, 0.2) ;\n
                         border: 4px inset blue;\n
                         "

    lineEdit_city_to: "font: 22pt \"Times\";\n
                       color:#00FFFF ;\n
                       background-color: rgba(0, 0, 128, 0.2) ;\n
                       border: 4px inset blue;\n
                       "

    lineEdit_priority: "font: 22pt \"Times\";\n
                        color:#00FFFF ;\n
                        background-color: rgba(0, 0, 128, 0.2) ;\n
                        border: 4px inset blue;\n
                        "

    lineEdit_markers: "font: 22pt \"Times\";\n
                       color:#00FFFF ;\n
                       background-color: rgba(0, 0, 128, 0.2) ;\n
                       border: 4px inset blue;\n
                       "

    lineEdit_map: "font: 22pt \"Times\";\n
                   color:#00FFFF ;\n
                   background-color: rgba(0, 0, 128, 0.2) ;\n
                   border: 4px inset blue;\n
                   "

date_base:
  airports_from: /Users/admin/PycharmProjects/AirPlan/Data/db/airports_from.txt
  airports_to: /Users/admin/PycharmProjects/AirPlan/Data/db/airports_to.txt
  routes: /Users/admin/PycharmProjects/AirPlan/Data/db/routes.txt

tmp:
  lines1: /Users/admin/PycharmProjects/AirPlan/Data/tmp/lines.txt
  lines2: /Users/admin/PycharmProjects/AirPlan/Data/tmp/lines2.txt
  lines3: /Users/admin/PycharmProjects/AirPlan/Data/tmp/lines3.txt
  FeatureGroup: /Users/admin/PycharmProjects/AirPlan/Data/tmp/FeatureGroup.html


